CREATE TABLE `COMPOUND_INTEREST_TABLES`.`3` (
`n` INT NOT NULL,
`F/P` FLOAT NOT NULL,
`P/F` FLOAT NOT NULL,
`A/F` FLOAT NOT NULL,
`A/P` FLOAT NOT NULL,
`F/A` FLOAT NOT NULL,
`P/A` FLOAT NOT NULL,
`A/G` FLOAT NOT NULL,
`P/G` FLOAT NOT NULL, PRIMARY KEY (`n`));